[2024-05-05T15:43:54.401+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T15:43:54.422+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.delete_entry_group manual__2024-05-05T15:42:35.204677+00:00 [queued]>
[2024-05-05T15:43:54.429+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.delete_entry_group manual__2024-05-05T15:42:35.204677+00:00 [queued]>
[2024-05-05T15:43:54.429+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T15:43:54.445+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): delete_entry_group> on 2024-05-05 15:42:35.204677+00:00
[2024-05-05T15:43:54.455+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T15:43:54.458+0000] {standard_task_runner.py:63} INFO - Started process 321 to run task
[2024-05-05T15:43:54.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'delete_entry_group', 'manual__2024-05-05T15:42:35.204677+00:00', '--job-id', '38', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmppv3dxw2i']
[2024-05-05T15:43:54.465+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask delete_entry_group
[2024-05-05T15:43:54.531+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.delete_entry_group manual__2024-05-05T15:42:35.204677+00:00 [running]> on host edcd6c8e3dad
[2024-05-05T15:43:54.684+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='delete_entry_group' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T15:42:35.204677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T15:42:35.204677+00:00'
[2024-05-05T15:43:54.686+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T15:43:54.687+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T15:43:54.687+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo delete_entry_group']
[2024-05-05T15:43:54.704+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T15:43:54.707+0000] {subprocess.py:93} INFO - delete_entry_group
[2024-05-05T15:43:54.708+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T15:43:54.709+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T15:43:54.755+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=delete_entry_group, execution_date=20240505T154235, start_date=20240505T154354, end_date=20240505T154354
[2024-05-05T15:43:54.801+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T15:43:54.818+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-05T15:43:54.825+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
